# Generated by Django 3.2.15 on 2022-08-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggaldibuat', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Tertunda', 'Tertunda'), ('Keluar untuk pengiriman', 'Keluar untuk pengiriman'), ('Terkirim', 'Terkirim')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('harga', models.PositiveIntegerField(null=True)),
                ('kategori', models.CharField(choices=[('dalam ruangan', 'dalam ruangan'), ('luar ruangan', 'luar ruangan')], max_length=200, null=True)),
                ('deskripsi', models.CharField(max_length=200, null=True)),
                ('tanggaldibuat', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
