# Generated by Django 3.2.15 on 2022-08-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memesan_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesan',
            name='pelanggan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pelanggan'),
        ),
        migrations.AddField(
            model_name='memesan',
            name='produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.produk'),
        ),
    ]
