# Generated by Django 3.2.15 on 2022-08-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220830_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memesan',
            name='tags',
        ),
        migrations.AddField(
            model_name='produk',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
